const resources=[
 {id:'bus',name:'محطة حافلة',price:.5,info:'40 شخصًا · نطاق 600م',icon:'🚌',color:'#148d80'},
 {id:'metro',name:'محطة مترو',price:8,info:'600 شخص · نطاق 2كم',icon:'🚇',color:'#365f91'},
 {id:'park',name:'حديقة صغيرة',price:1,info:'120 زائرًا · حي واحد',icon:'🌳',color:'#5c9857'},
 {id:'school',name:'مدرسة',price:3,info:'450 طالبًا · حي واحد',icon:'🏫',color:'#d2a02d'},
 {id:'clinic',name:'عيادة',price:2,info:'150 مراجعًا · حيّان',icon:'✚',color:'#c94f5d'},
 {id:'hospital',name:'مستشفى',price:5,info:'500 مراجع · المدينة',icon:'🏥',color:'#b43d51'},
 {id:'youth',name:'مركز شبابي',price:2.5,info:'200 شاب · نطاق 1.5كم',icon:'⚽',color:'#7455a5'},
 {id:'market',name:'سوق حي',price:1.5,info:'35 متجرًا · حي واحد',icon:'🛍',color:'#bb6536'},
 {id:'mall',name:'مركز تجاري',price:5,info:'120 متجرًا · المدينة',icon:'🏬',color:'#435a8e'}];
const labels=[['حي الورود',18,63],['حي الياسمين',43,42],['حي الأزهار',65,55],['حي البستان — الحي الجديد',57,86],['المنطقة الصناعية',84,30],['وسط البلد',66,68]];
let state=JSON.parse(localStorage.getItem('mdr-public-demo')||'null')||{budget:100,items:[],team:'فريق التجربة',notice:''};let selected=null;let moving=null;
const $=s=>document.querySelector(s),app=$('#app'),save=()=>localStorage.setItem('mdr-public-demo',JSON.stringify(state)),rid=id=>resources.find(r=>r.id===id),uid=()=>Math.random().toString(36).slice(2,9);
function shell(content,mode){app.innerHTML=`<header class="top"><img src="./assets/mdr-logo.png"><div><b>مدينة الربيع</b><small>${mode}</small></div><span class="mode">نسخة عامة تجريبية</span></header>${content}`}
function login(){app.innerHTML=`<main class="login"><section class="card"><div class="brand"><img src="./assets/mdr-logo.png"><div><b>مدينة الربيع</b><small>نسخة العرض التفاعلية</small></div></div><h1>اختر وضع التجربة</h1><p>هذه النسخة تستخدم بيانات تجريبية داخل هذا المتصفح ولا تتصل بخرائط الفرق الحقيقية.</p><div class="choices"><button id="team">دخول الفريق</button><button id="admin">دخول الإدارة</button></div><small class="hint">رمز الإدارة التجريبي: MDR</small></section></main>`;$('#team').onclick=team;$('#admin').onclick=()=>{const c=prompt('رمز الإدارة');c==='MDR'?admin():alert('الرمز غير صحيح')}}
function spent(){return state.items.reduce((n,x)=>n+rid(x.rid).price,0)}function toast(x){const t=document.createElement('div');t.className='toast';t.textContent=x;document.body.append(t);setTimeout(()=>t.remove(),1500)}
function valid(x,y){return !(y<18||x<16&&y<30)}
function team(){shell(`<div class="layout"><aside class="panel"><h2>مكتبة الموارد</h2><p>اسحب المورد إلى الخريطة أو انقر عليه لإضافته.</p><div class="resources">${resources.map(r=>`<article class="resource" draggable="true" data-r="${r.id}"><span class="icon" style="--c:${r.color}">${r.icon}</span><div><b>${r.name}</b><small>${r.info}</small></div><strong>${r.price}م</strong></article>`).join('')}</div></aside><section class="board"><div class="budget"><div class="metric"><small>تكلفة الخطة</small><b id="spent"></b></div><div class="metric"><small>الرصيد المتبقي</small><b id="left"></b></div><div class="metric"><small>سقف الميزانية</small><b>${state.budget} مليون</b></div></div>${state.notice?`<div class="notice">${state.notice}</div>`:''}<div class="map-wrap"><div class="map" id="map"><img src="./assets/city-map.jpg">${labels.map(l=>`<span class="label" style="left:${l[1]}%;top:${l[2]}%">${l[0]}</span>`).join('')}</div></div><div class="tools"><button id="delete" disabled>حذف واسترداد</button><button id="undo">تراجع</button><button id="resetview">إلغاء التحديد</button><button id="back">تبديل الحساب</button></div></section></div>`,state.team);renderItems();document.querySelectorAll('.resource').forEach(el=>{el.ondragstart=e=>e.dataTransfer.setData('rid',el.dataset.r);el.onclick=()=>add(el.dataset.r,50,52)});const map=$('#map');map.ondragover=e=>e.preventDefault();map.ondrop=e=>{e.preventDefault();const b=map.getBoundingClientRect();add(e.dataTransfer.getData('rid'),(e.clientX-b.left)/b.width*100,(e.clientY-b.top)/b.height*100)};map.onpointermove=e=>{if(!moving)return;const b=map.getBoundingClientRect(),x=(e.clientX-b.left)/b.width*100,y=(e.clientY-b.top)/b.height*100;if(valid(x,y)){const p=state.items.find(i=>i.id===moving);p.x=x;p.y=y;save();renderItems()}};map.onpointerup=()=>moving=null;$('#delete').onclick=()=>{state.items=state.items.filter(x=>x.id!==selected);selected=null;save();renderItems();toast('عادت قيمة المورد')};$('#undo').onclick=()=>{state.items.pop();save();renderItems()};$('#resetview').onclick=()=>{selected=null;renderItems()};$('#back').onclick=login;metrics()}
function add(rid,x,y){if(!valid(x,y)){toast('لا يمكن وضع المورد في البحر');return}state.items.push({id:uid(),rid,x,y});save();renderItems();metrics()}
function renderItems(){const map=$('#map');if(!map)return;map.querySelectorAll('.placed').forEach(x=>x.remove());state.items.forEach(p=>{const r=rid(p.rid),b=document.createElement('button');b.className='placed'+(selected===p.id?' selected':'');b.style.cssText=`left:${p.x}%;top:${p.y}%;--c:${r.color}`;b.innerHTML=`${r.icon}<span>${r.name} · ${r.price}م</span>`;b.onpointerdown=e=>{e.stopPropagation();selected=p.id;moving=p.id;b.setPointerCapture(e.pointerId);renderItems();$('#delete').disabled=false};map.append(b)});const d=$('#delete');if(d)d.disabled=!selected;metrics()}
function metrics(){const s=$('#spent'),l=$('#left');if(!s)return;const n=spent(),left=state.budget-n;s.textContent=n+' مليون';l.textContent=left+' مليون';l.className=left<0?'negative':''}
function admin(){shell(`<main class="admin"><div><h1>لوحة الإدارة التجريبية</h1><p>التعديلات تخص هذا المتصفح فقط.</p></div><div class="admin-grid"><article><h2>الفريق</h2><label>اسم الفريق<input id="teamname" value="${state.team}"></label><button id="savename">حفظ الاسم</button></article><article><h2>الميزانية</h2><p>السقف الحالي: <b>${state.budget} مليون</b></p><button class="danger" id="cut">خفضها إلى 70 مليونًا</button></article><article><h2>رسالة للفريق</h2><label>التعليمات<input id="message" value="${state.notice}"></label><button id="send">إرسال</button></article></div><article><h2>ملخص الخريطة</h2><p>عدد الموارد: <b>${state.items.length}</b> · التكلفة: <b>${spent()} مليون</b> · الرصيد: <b>${state.budget-spent()} مليون</b></p><button id="openmap">مشاهدة خريطة الفريق</button> <button id="logout">العودة للدخول</button></article></main>`,'حساب الإدارة');$('#savename').onclick=()=>{state.team=$('#teamname').value;save();admin()};$('#cut').onclick=()=>{state.budget=70;state.notice='خُفضت ميزانية الحل إلى 70 مليونًا. راجعوا الأولويات.';save();admin()};$('#send').onclick=()=>{state.notice=$('#message').value;save();toast('أُرسلت الرسالة')};$('#openmap').onclick=team;$('#logout').onclick=login}
login();
