const resources=[
 ['bus','محطة حافلة','التنقل',.5,'40 شخصًا · نطاق 600م','🚌','#148d80'],['metro','محطة مترو','التنقل',8,'600 شخص · نطاق 2كم','🚇','#365f91'],['park','حديقة صغيرة','الأماكن',1,'120 زائرًا · حي واحد','🌳','#5c9857'],['bigpark','حديقة كبيرة','الأماكن',4,'500 زائر · حيّان','🌲','#357747'],['play','ملعب','الأماكن',2,'80 لاعبًا · نطاق 1كم','⚽','#d9782c'],['school','مدرسة','الخدمات',3,'450 طالبًا · حي واحد','🏫','#d2a02d'],['clinic','عيادة','الخدمات',2,'150 مراجعًا · حيّان','✚','#c94f5d'],['hospital','مستشفى','الخدمات',5,'500 مراجع · المدينة','🏥','#b43d51'],['youth','مركز شبابي','الخدمات',2.5,'200 شاب · نطاق 1.5كم','🏀','#7455a5'],['market','سوق حي','النشاط',1.5,'35 متجرًا · حي واحد','🛍','#bb6536'],['night','سوق مسائي','النشاط',1,'24 كشكًا · المنطقة','🌙','#9c4c88'],['mall','مركز تجاري','النشاط',5,'120 متجرًا · المدينة','🏬','#435a8e']
].map(x=>({id:x[0],name:x[1],cat:x[2],price:x[3],info:x[4],icon:x[5],color:x[6]}));
const labels=[['حي الورود',18,63],['حي الياسمين',43,42],['حي الأزهار',65,55],['حي البستان · الحي الجديد',57,86],['المنطقة الصناعية',84,30],['وسط البلد',66,68]];
const defaults=()=>({notice:'',cut:false,teams:[{id:'falcons',name:'فريق الصقور',code:'MDR-241',budget:100,items:[],locked:false,approved:false,history:[]},{id:'stars',name:'فريق النجوم',code:'MDR-527',budget:100,items:[],locked:false,approved:false,history:[]}]});
let state=JSON.parse(localStorage.getItem('mdr-demo-v3')||'null')||defaults(),selected=null,moving=null,zoom=1,cat='الكل';
const $=s=>document.querySelector(s),app=$('#app'),uid=()=>Math.random().toString(36).slice(2,9),res=id=>resources.find(r=>r.id===id),getTeam=id=>state.teams.find(t=>t.id===id),save=()=>localStorage.setItem('mdr-demo-v3',JSON.stringify(state));
function shell(body,title,role){app.innerHTML=`<header class="top"><div class="top-brand"><img src="./mdr-logo.png"><div><b>مدينة الربيع</b><small>${title}</small></div></div><span class="role">${role}</span></header>${body}`}
function toast(text,type=''){const n=document.createElement('div');n.className=`toast ${type}`;n.textContent=text;document.body.append(n);setTimeout(()=>n.remove(),1800)}
function log(t,label){t.history.unshift({label,time:new Date().toLocaleTimeString('ar-SA',{hour:'2-digit',minute:'2-digit'})});t.history=t.history.slice(0,20)}
function login(){app.innerHTML=`<main class="login"><section class="login-card"><div class="brand-lockup"><img src="./mdr-logo.png"><div><b>مدينة الربيع</b><span>نسخة تجربة اللعب</span></div></div><h1>الدخول إلى الخريطة</h1><p>استخدم رمز فريق تجريبي أو افتح لوحة الإدارة.</p><label>رمز الفريق<input id="code" placeholder="MDR-241"></label><button class="primary" id="enter">دخول الفريق</button><button class="text-button" id="admin">دخول الإدارة</button><div class="demo-codes"><span>رموز التجربة</span><button data-code="MDR-241">MDR-241</button><button data-code="MDR-527">MDR-527</button></div></section></main>`;const enter=()=>{const t=state.teams.find(x=>x.code.toUpperCase()===$('#code').value.trim().toUpperCase());t?teamView(t.id):toast('رمز الفريق غير صحيح','error')};$('#enter').onclick=enter;$('#code').onkeydown=e=>e.key==='Enter'&&enter();document.querySelectorAll('[data-code]').forEach(b=>b.onclick=()=>$('#code').value=b.dataset.code);$('#admin').onclick=()=>prompt('رمز الإدارة')==='MDR'?adminView():toast('رمز الإدارة غير صحيح','error')}
const spent=t=>t.items.reduce((n,i)=>n+(res(i.rid)?.price||0),0);
const valid=(x,y)=>!(y<17||(x<15&&y<31)||(x>62&&x<76&&y<20))&&x>1&&x<99&&y>2&&y<98;
function links(t){const b=t.items.filter(i=>i.rid==='bus');return b.flatMap((a,i)=>b.slice(i+1).filter(c=>Math.hypot(a.x-c.x,a.y-c.y)<18).map(c=>`<line x1="${a.x}" y1="${a.y}" x2="${c.x}" y2="${c.y}"/>`)).join('')}
function teamView(id){const t=getTeam(id);if(!t)return login();const left=t.budget-spent(t);shell(`<main class="game"><aside class="library"><div class="library-head"><span>مكتبة الموارد</span><b>ابنوا خطتكم</b></div><div class="categories">${['الكل','التنقل','الأماكن','الخدمات','النشاط'].map(c=>`<button data-cat="${c}" class="${cat===c?'active':''}">${c}</button>`).join('')}</div><div class="resources">${resources.filter(r=>cat==='الكل'||r.cat===cat).map(r=>`<article class="resource" draggable="${!t.locked}" data-rid="${r.id}"><span class="resource-art" style="--resource:${r.color}">${r.icon}</span><div><b>${r.name}</b><small>${r.info}</small></div><strong>${r.price}م</strong></article>`).join('')}</div></aside><section class="workspace"><div class="status-row"><div><small>تكلفة الخطة</small><b>${spent(t)} مليون</b></div><div class="${left<0?'danger-text':''}"><small>الرصيد المتبقي</small><b>${left} مليون</b></div><div><small>سقف الميزانية</small><b>${t.budget} مليون</b></div><span class="save-state">● محفوظ تلقائيًا</span></div>${state.notice?`<div class="mission-notice"><b>تحديث المهمة</b><span>${state.notice}</span></div>`:''}${left<0?`<div class="over-budget">تجاوزتم الميزانية بـ ${Math.abs(left)} مليون. خفّضوا التكلفة قبل الاعتماد.</div>`:''}<div class="map-toolbar"><button id="out">−</button><b>${Math.round(zoom*100)}%</b><button id="in">+</button><button id="fit">ملاءمة</button><span>مرّر داخل الخريطة بعد التكبير</span></div><div class="map-viewport"><div class="map" id="map" style="width:${zoom*100}%"><img src="./city-map.jpg" draggable="false">${labels.map(l=>`<span class="map-label" style="left:${l[1]}%;top:${l[2]}%">${l[0]}</span>`).join('')}<svg class="connections" viewBox="0 0 100 100" preserveAspectRatio="none">${links(t)}</svg></div></div><div class="actionbar"><button id="remove" disabled>حذف واسترداد</button><button id="clear">إلغاء التحديد</button><button id="approve" class="approve" ${left<0||t.locked?'disabled':''}>${t.approved?'الخطة معتمدة':'اعتماد الخطة'}</button><button id="logout">خروج</button></div></section></main>`,t.name,t.approved?'خطة معتمدة':'حساب فريق');wireTeam(t)}
function point(e,map){const b=map.getBoundingClientRect();return{x:(e.clientX-b.left)/b.width*100,y:(e.clientY-b.top)/b.height*100}}
function wireTeam(t){document.querySelectorAll('[data-cat]').forEach(b=>b.onclick=()=>{cat=b.dataset.cat;teamView(t.id)});document.querySelectorAll('.resource').forEach(el=>{el.ondragstart=e=>{if(t.locked)return e.preventDefault();e.dataTransfer.setData('rid',el.dataset.rid)};el.onclick=()=>{if(t.locked)return toast('الخريطة مجمدة','error');toast('اختر مكان المورد على الخريطة');const map=$('#map');map.classList.add('placing');map.onclick=e=>{map.onclick=null;map.classList.remove('placing');const p=point(e,map);add(t,el.dataset.rid,p.x,p.y)}}});const map=$('#map');map.ondragover=e=>e.preventDefault();map.ondrop=e=>{e.preventDefault();const p=point(e,map);add(t,e.dataTransfer.getData('rid'),p.x,p.y)};map.onpointermove=e=>{if(!moving||t.locked)return;const p=point(e,map),item=t.items.find(i=>i.id===moving);if(item&&valid(p.x,p.y)){item.x=p.x;item.y=p.y;save();draw(t)}};map.onpointerup=()=>{if(moving){log(t,'تحريك مورد');save()}moving=null};$('#in').onclick=()=>{zoom=Math.min(1.8,zoom+.15);teamView(t.id)};$('#out').onclick=()=>{zoom=Math.max(1,zoom-.15);teamView(t.id)};$('#fit').onclick=()=>{zoom=1;teamView(t.id)};$('#remove').onclick=()=>remove(t);$('#clear').onclick=()=>{selected=null;draw(t)};$('#approve').onclick=()=>{if(t.approved)return;t.approved=t.locked=true;log(t,'اعتماد الخطة');save();teamView(t.id);toast('تم اعتماد الخطة')};$('#logout').onclick=login;draw(t)}
function add(t,rid,x,y){if(!rid)return;if(!valid(x,y))return toast('هذا الموقع غير صالح','error');t.items.push({id:uid(),rid,x,y});log(t,`إضافة ${res(rid).name}`);save();teamView(t.id)}
function draw(t){const map=$('#map');if(!map)return;map.querySelectorAll('.placed').forEach(e=>e.remove());t.items.forEach(i=>{const r=res(i.rid),b=document.createElement('button');b.className=`placed type-${r.id}${selected===i.id?' selected':''}`;b.style.cssText=`left:${i.x}%;top:${i.y}%;--resource:${r.color}`;b.innerHTML=`<i>${r.icon}</i><span>${r.name}<small>${r.price} مليون</small></span>`;b.onpointerdown=e=>{e.stopPropagation();if(t.locked)return;selected=i.id;moving=i.id;b.setPointerCapture(e.pointerId);draw(t)};map.append(b)});$('#remove').disabled=!selected||t.locked}
function remove(t){const i=t.items.find(x=>x.id===selected);if(!i)return;t.items=t.items.filter(x=>x.id!==selected);log(t,`حذف ${res(i.rid).name}`);selected=null;save();teamView(t.id);toast('استُردت قيمة المورد')}
function adminView(active=state.teams[0]?.id){const t=getTeam(active)||state.teams[0];shell(`<main class="admin"><aside class="admin-nav"><h2>مركز التحكم</h2><button class="active">الفرق والخرائط</button><button id="newTeam">إضافة فريق</button><button id="notice">إرسال تعليمات</button><button id="cut" class="danger-button">خفض الميزانيات</button><button id="reset">إعادة ضبط التجربة</button><button id="exit">خروج</button></aside><section class="admin-main"><div class="admin-title"><div><span>متابعة الفرق</span><h1>الفرق والخرائط</h1></div><div class="summary-pill">${state.teams.length} فرق · ${state.teams.filter(x=>x.approved).length} معتمدة</div></div><div class="team-cards">${state.teams.map(x=>{const l=x.budget-spent(x);return `<button data-team="${x.id}" class="team-card ${t?.id===x.id?'active':''}"><b>${x.name}</b><small>${x.code}</small><span class="${l<0?'danger-text':''}">${l}م متبقية</span></button>`}).join('')}</div>${t?adminTeam(t):'<div class="empty">أنشئ فريقًا للبدء.</div>'}</section></main>`, 'لوحة الإدارة','مدير التجربة');wireAdmin(t)}
function adminTeam(t){const left=t.budget-spent(t);return `<div class="admin-grid"><article class="admin-map-card"><div class="admin-map"><img src="./city-map.jpg">${t.items.map(i=>{const r=res(i.rid);return `<span style="left:${i.x}%;top:${i.y}%;--resource:${r.color}">${r.icon}</span>`}).join('')}</div></article><article class="team-control"><div class="control-head"><div><span>الفريق المحدد</span><h2>${t.name}</h2><small>${t.code}</small></div><strong class="${left<0?'danger-text':''}">${left}م</strong></div><dl><div><dt>تكلفة الخطة</dt><dd>${spent(t)}م</dd></div><div><dt>عدد الموارد</dt><dd>${t.items.length}</dd></div><div><dt>الحالة</dt><dd>${t.approved?'معتمدة':t.locked?'مجمدة':'قيد العمل'}</dd></div></dl><div class="control-actions"><button id="lock">${t.locked&&!t.approved?'فتح الخريطة':'تجميد الخريطة'}</button><button id="reopen" ${!t.approved?'disabled':''}>إعادة فتح الخطة</button><button id="rename">الاسم والرمز</button><button id="delete" class="danger-button">حذف الفريق</button></div><div class="auto-score"><span>تقييم إرشادي للأدمن فقط</span><b>${score(t)}/100</b><p>${notes(t,left)}</p></div><div class="history"><h3>آخر العمليات</h3>${t.history.slice(0,5).map(h=>`<div><span>${h.label}</span><small>${h.time}</small></div>`).join('')||'<p>لا توجد عمليات بعد.</p>'}</div></article></div>`}
const score=t=>Math.min(92,25+t.items.length*4+new Set(t.items.map(i=>res(i.rid)?.cat)).size*8+(t.items.some(i=>i.rid==='bus')?6:0));
function notes(t,left){return [new Set(t.items.map(i=>res(i.rid)?.cat)).size>=3?'تنوع جيد':'التنوع محدود',t.items.filter(i=>i.rid==='bus').length>=2?'النقل قابل للربط':'النقل محدود',left<0?`تجاوز ${Math.abs(left)}م`:'ضمن الميزانية'].join(' · ')}
function wireAdmin(t){document.querySelectorAll('[data-team]').forEach(b=>b.onclick=()=>adminView(b.dataset.team));$('#exit').onclick=login;$('#newTeam').onclick=()=>{const name=prompt('اسم الفريق'),code=name&&prompt('رمز الدخول',`MDR-${Math.floor(100+Math.random()*900)}`);if(!name||!code)return;const n={id:uid(),name,code,budget:state.cut?70:100,items:[],locked:false,approved:false,history:[]};state.teams.push(n);save();adminView(n.id)};$('#notice').onclick=()=>{const m=prompt('التعليمات لجميع الفرق',state.notice);if(m===null)return;state.notice=m;save();adminView(t?.id)};$('#cut').onclick=()=>{const affected=state.teams.filter(x=>spent(x)>70).length;if(!confirm(`خفض الميزانيات إلى 70 مليونًا؟ ${affected} فريق سيتجاوز الحد.`))return;state.cut=true;state.notice='خُفضت ميزانية الحل إلى 70 مليونًا. راجعوا الأولويات.';state.teams.forEach(x=>{x.budget=70;log(x,'خفض الميزانية إلى 70م')});save();adminView(t?.id)};$('#reset').onclick=()=>{if(confirm('إعادة جميع بيانات التجربة؟')){state=defaults();save();adminView()}};if(!t)return;$('#lock').onclick=()=>{t.locked=!t.locked;save();adminView(t.id)};$('#reopen').onclick=()=>{t.approved=false;t.locked=false;log(t,'إعادة فتح الخطة');save();adminView(t.id)};$('#rename').onclick=()=>{const n=prompt('اسم الفريق',t.name),c=prompt('الرمز',t.code);if(n)t.name=n;if(c)t.code=c;save();adminView(t.id)};$('#delete').onclick=()=>{if(confirm(`حذف ${t.name}؟`)){state.teams=state.teams.filter(x=>x.id!==t.id);save();adminView()}}}
login();
